graph TD
    CollaborationParametragePage.js --> firebase-service
    ConfirmationPage.js --> preContratService
    ConfirmationPage.js --> tachesService
    ConfirmationPage.js --> firebase-service
    ContratGenerationNewPage.js --> firebase-service
    ContratGenerationNewPage.js --> firebase-service
    ContratGenerationNewPage.js --> preContratService
    ContratGenerationPage.js --> firebase-service
    ContratGenerationPage.js --> firebase-service
    ContratRedactionPage.js --> firebase-service
    ContratRedactionPage.js --> firebase-service
    ContratRedactionPage.js --> contratService
    ContratsPage.js --> firebase-service
    ContratsPage.js --> firebase-service
    ContratsPage.js --> contratService
    DateCreationPage.js --> firebase-service
    FactureGeneratorPage.js --> firebase-service
    FactureGeneratorPage.js --> contratService
    FactureGeneratorPage.js --> factureService
    FacturesPage.js --> firebase-service
    FacturesPage.js --> firebase-service
    FacturesPage.js --> factureService
    FestivalsDatesPage.js --> firebase-service
    LoginPage.js --> firebase-service
    PreContratGenerationPage.js --> firebase-service
    PreContratGenerationPage.js --> firebase-service
    ProjetsPage.js --> firebase-service
    TachesPage.js --> firebase-service
    contratTemplatesEditPage.js --> firebase-service
    contratTemplatesPage.js --> firebase-service
    factureTemplatesEditPage.js --> firebase-service
    factureTemplatesPage.js --> firebase-service
    contactCreationFromForms.test.js -.-> firebase-service
    ContactFormUnified.js -.-> firebase-service
    EchangeForm.js -.-> historiqueEchangesService
    ContactForm.js -.-> firebase-service
    HybridFormatNormalizer.js -.-> firebase-service
    HybridFormatNormalizer.js -.-> firebase-service
    DevisForm.js -.-> structureService
    DevisForm.js -.-> projetService
    DevisForm.js -.-> contactService
    DevisForm.js -.-> collaborateurService
    FormGenerator.js -.-> firebase-service
    FormGenerator.js -.-> brevoTemplateService
    PublicContactForm.js -.-> firebase-service
    PreContratFormContainer.js -.-> preContratService
    useConcertForm.js -.-> bidirectionalRelationsService
    useConcertFormWithRelations.js -.-> firebase-service
    useConcertFormsManagement.js -.-> firebase-service
    useFormTokenValidation.js -.-> firebase-service
    useFormTokenValidation.js -.-> preContratService
    useFormValidationData.js -.-> firebase-service
    useLieuForm.js -.-> bidirectionalRelationsService
    useEntrepriseForm.js -.-> firebase-service
    useEntrepriseForm.js -.-> firebase-service
    useStructureForm.js -.-> bidirectionalRelationsService
    FormResponsePage.js -.-> firebase-service
    PreContratFormResponsePage.js -.-> firebase-service
    PreContratFormResponsePage.js -.-> preContratService
    useOrganization ==> 115_components
    useAuth ==> 31_components
    useTabs ==> 29_components
    useContext ==> 8_components
